#!/usr/bin/env bash
# scripts/check-prereqs.sh — prerequisite verifier for rag-nq-showcase.
#
# Verifies the tools required for the dev/build/test loop are installed and
# at the required versions. Prints one line per check (✓ or ✗) and exits 0
# if all pass, non-zero with diagnostics if any fail.
#
# Also runs a regression check that no runtime code in scripts/ or hooks/
# reads from .template.answers (VOI-189; .template.answers is stale and
# outside Claude's writable scope per PLAN.md §6).
#
# Usage:
#   bash scripts/check-prereqs.sh
#
set -uo pipefail

# Run from repo root regardless of where the user invokes this from, so
# relative paths in checks (scripts/, hooks/, node_modules/.bin/) resolve
# correctly.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

fail_count=0

# -- helpers ----------------------------------------------------------------

pass() { printf "✓ %s\n" "$1"; }

fail() {
  printf "✗ %s\n" "$1" >&2
  if [ -n "${2-}" ]; then
    printf "    install: %s\n" "$2" >&2
  fi
  fail_count=$((fail_count + 1))
}

info() { printf "ℹ %s\n" "$1"; }

# version_ge X Y → 0 if X ≥ Y, 1 otherwise. Splits each on '.', compares
# components numerically. Tolerates non-numeric suffixes (e.g. "3.11.0rc1")
# by stripping the first non-digit and everything after it within each
# component. Uses POSIX awk so it works on default macOS/BSD/Linux without
# requiring GNU coreutils (which `sort -V -C` would).
version_ge() {
  awk -v a="$1" -v b="$2" 'BEGIN {
    n = split(a, ax, ".")
    m = split(b, bx, ".")
    max = (n > m) ? n : m
    for (i = 1; i <= max; i++) {
      av = (i <= n) ? ax[i] : 0
      bv = (i <= m) ? bx[i] : 0
      sub(/[^0-9].*/, "", av); sub(/[^0-9].*/, "", bv)
      av += 0; bv += 0
      if (av > bv) exit 0
      if (av < bv) exit 1
    }
    exit 0  # equal
  }'
}

# -- checks -----------------------------------------------------------------

# node ≥ 22.22.3 (required by likec4@1.57 per its engines field; bumped per VOI-225 PR #7 Codex P1)
if command -v node >/dev/null 2>&1; then
  v="$(node --version | sed 's/^v//')"
  if version_ge "$v" "22.22.3"; then
    pass "node $v (≥ 22.22.3 required)"
  else
    fail "node $v (need ≥ 22.22.3)" "https://nodejs.org/ — or 'brew install node'"
  fi
else
  fail "node not on PATH" "https://nodejs.org/ — or 'brew install node'"
fi

# npm — bundled with node.
if command -v npm >/dev/null 2>&1; then
  pass "npm $(npm --version)"
else
  fail "npm not on PATH" "ships with node; reinstall node"
fi

# uv (Python tooling)
if command -v uv >/dev/null 2>&1; then
  pass "uv $(uv --version 2>&1 | awk '{print $2}')"
else
  fail "uv not on PATH" "'brew install uv' or 'curl -LsSf https://astral.sh/uv/install.sh | sh'"
fi

# python3 ≥ 3.11
if command -v python3 >/dev/null 2>&1; then
  v="$(python3 --version 2>&1 | awk '{print $2}')"
  if version_ge "$v" "3.11.0"; then
    pass "python3 $v (≥ 3.11 required)"
  else
    fail "python3 $v (need ≥ 3.11)" "'brew install python@3.12' — or install via uv"
  fi
else
  fail "python3 not on PATH" "'brew install python@3.12'"
fi

# git-lfs — version line looks like 'git-lfs/3.4.0 (GitHub; darwin arm64; ...)'.
if git lfs version >/dev/null 2>&1; then
  v="$(git lfs version 2>&1 | sed -n 's|^git-lfs/\([^ ]*\).*|\1|p')"
  [ -n "$v" ] || v="(installed; version unparsed)"
  pass "git-lfs $v"
else
  fail "git-lfs not installed" "'brew install git-lfs && git lfs install'"
fi

# likec4 — prefer local install (node_modules/.bin) once package.json lands
# (P0.3); fall back to a global install for early-Phase-0 development.
if [ -x "node_modules/.bin/likec4" ]; then
  v="$(node_modules/.bin/likec4 --version 2>&1 | tail -n 1)"
  pass "likec4 $v (local)"
elif command -v likec4 >/dev/null 2>&1; then
  v="$(likec4 --version 2>&1 | tail -n 1)"
  pass "likec4 $v (global)"
else
  fail "likec4 not on PATH and not in node_modules/.bin/" \
       "'npm install' once package.json lands (P0.3) — or 'npm i -g likec4' for now"
fi

# /understand — Claude Code slash command from the understand-anything
# plugin. This bash script cannot introspect Claude Code's loaded
# skills/plugins, so we surface a verification hint instead of a hard
# check. (The plugin must be installed in the Claude Code session that
# runs the knowledge-graph regeneration step.)
info "/understand is a Claude Code skill — verify in-session by typing '/understand' (requires the understand-anything plugin)"

# -- regression: no runtime reads of .template.answers ---------------------
#
# .template.answers is generated by orc-temp's init.sh at template install
# time. PLAN.md §6 designates it as OUTSIDE Claude's writable scope and
# intentionally stale — values were baked into hooks/scripts at generation
# time and the file is unused at runtime thereafter. This check prevents a
# future contributor from accidentally re-introducing a runtime dependency
# on the stale file (which would silently rot).
#
# Comments are fine (lines starting with `//` or `#` after `file:line:` are
# excluded). The grep deliberately excludes THIS script — searching for
# `.template.answers` in scripts/check-prereqs.sh would otherwise self-match
# on the pattern argument below.
violations="$(grep -rIn --exclude='check-prereqs.sh' '\.template\.answers' scripts/ hooks/ 2>/dev/null \
              | grep -vE '^[^:]+:[0-9]+:[[:space:]]*(//|#)' || true)"
if [ -n "$violations" ]; then
  fail "runtime reference to .template.answers detected (file is stale and outside Claude's writable scope)" \
       "remove the runtime read; .template.answers is updated via the template tooling, not this repo"
  printf "%s\n" "$violations" | sed 's/^/    /' >&2
else
  pass "no runtime reads of .template.answers (regression check)"
fi

# -- verdict ----------------------------------------------------------------

echo
if [ "$fail_count" -eq 0 ]; then
  echo "all prerequisites satisfied."
  exit 0
else
  echo "$fail_count prerequisite(s) missing or wrong version — see diagnostics above." >&2
  exit 1
fi
